const ACTIONS={
    GET_ALL_CATAGORIES:"GET_ALL_CATAGORIES",
    GET_CATAGORY_PPRODUCTS:"GET_CATAGORY_PPRODUCTS",
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS" ,
    GET_PRODUCT_BY_ID:"GET_PRODUCT_BY_ID" 
}
export default ACTIONS;